### PR TITLE
Fixed document error, it should be C compiler.

### PR DESCRIPTION
**Pull request by peixinchen**
I just installed confluent-kafka by pip, but i got a error that compiler is gcc but enviroment is cpp. And then I fixed.

### CODE REVIEW

**Comment by peixinchen** [comment]
So how do i sign the CLA, I neither got it from README nor document.

**Comment by ewencp** [comment]
@peixinchen Sorry about that, for some reason the link was not removed. You can find the CLA [here](http://clabot.confluent.io/cla).

**Comment by peixinchen** [comment]
@ewencp It's OK, and I signed CLA now, should I repush the commit to fire the clabot's check?

**Comment by ewencp** [comment]
@peixinchen You can post a message with [clabot:check] to have it validate for you, but I also just manually validated you signed it, so you should be good.

**Comment by peixinchen** [comment]
@ewencp Thanks a lot. I'm not good at English, so if the commit message is not suitable, let me know.

**Comment by edenhill** [comment]
Thank you @peixinchen !

**Pull request merged**
