### PR TITLE
Added metadata() method to Consumer and Producer to fetch broker meta…

### PR DESCRIPTION
**Pull request by davejohncole**
Tried to follow the coding style that was already present in the code.
This allows you to do something like the following:
```
producer = Producer(**{'bootstrap.servers': 'kafka'})
m = producer.metadata('Test.Topic', 5.0)
print 'Metadata:'
for b in m.brokers():
    print '  broker: id=%s, host=%r, port=%s' % (b.id(), b.host(), b.port())
for t in m.topics():
    print '  topic:  %r, error=%s' % (t.topic(), t.error())
    for p in t.partitions():
        print '    partition: id=%s, error=%s, leader=%s, replicas=%s, isrs=%s' \
                    % (p.id(), p.error(), p.leader(), p.replicas(), p.isrs())
```

### CODE REVIEW

**Comment by edenhill** [comment]
Sorry to say this but there is already a PR for adding the metadata API:
https://github.com/confluentinc/confluent-kafka-python/pull/309

**Comment by davejohncole** [comment]
Fair enough.

It seems to have stalled.  I just (urgently) need the functionality to be
there one way or another.

**Comment by davejohncole** [comment]
Looks like the `tests/test_threads.py::test_thread_safety` is flakey.  I do not have python3.4 or 3.5 so added a py36 setting to `tox.ini`.  The tests all pass locally with python3.6.

**Comment by erikbarbara** [comment]
@edenhill, if the code in this PR is kosher, can we proceed with it and reject #309. The other PR seems to have stalled out because of legal constraints.

**Comment by rnpridgeon** [comment]
Closing this one out as it would appear the blockers for #309 have been resolved and we have moved forward with the solution. The fix currently resides within the branch `foradminapi` and will be transitioned to `master` in the near future. 

Thank you again for your work on this.

**Pull request closed without merging**
