### PR TITLE
Include tests with source packages (#508)

### PR DESCRIPTION
**Pull request by rnpridgeon**

### CODE REVIEW

**Comment by rnpridgeon** [comment]
Seems to work fine 

tar -tvf /tmp/test/confluent-kafka-1.1.0rc2.tar.gz
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/
-rw-r--r--  0 ryan   staff     334 Jul 26 08:17 confluent-kafka-1.1.0rc2/PKG-INFO
-rw-r--r--  0 ryan   staff      21 Jul 15 06:31 confluent-kafka-1.1.0rc2/test-requirements.txt
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/tests/
-rw-r--r--  0 ryan   staff    9406 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/test_Admin.py
-rw-r--r--  0 ryan   staff    6429 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/test_misc.py
-rw-r--r--  0 ryan   staff    1603 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/test_TopicPartition.py
-rw-r--r--  0 ryan   staff    6072 Jul 15 06:31 confluent-kafka-1.1.0rc2/tests/test_Producer.py
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/tests/integration/
-rw-r--r--  0 ryan   staff       0 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/integration/__init__.py
-rwxr-xr-x  0 ryan   staff   45236 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/integration/integration_test.py
-rwxr-xr-x  0 ryan   staff    3245 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/test_docs.py
-rw-r--r--  0 ryan   staff    1486 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/test_KafkaError.py
-rw-r--r--  0 ryan   staff       0 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/__init__.py
-rw-r--r--  0 ryan   staff    2040 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/test_log.py
-rw-r--r--  0 ryan   staff     854 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/test_enums.py
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/tests/avro/
-rw-r--r--  0 ryan   staff    8415 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/avro/test_cached_client.py
-rw-r--r--  0 ryan   staff    4177 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/avro/test_mock_client.py
-rw-r--r--  0 ryan   staff    2637 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/avro/data_gen.py
-rw-r--r--  0 ryan   staff       0 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/avro/__init__.py
-rw-r--r--  0 ryan   staff    6175 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/avro/mock_registry.py
-rw-r--r--  0 ryan   staff    2980 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/avro/test_message_serializer.py
-rw-r--r--  0 ryan   staff    1392 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/avro/test_util.py
-rw-r--r--  0 ryan   staff    6266 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/avro/test_avro_producer.py
-rw-r--r--  0 ryan   staff    5001 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/avro/mock_schema_registry_client.py
-rw-r--r--  0 ryan   staff    1486 Mar 27 06:11 confluent-kafka-1.1.0rc2/tests/test_threads.py
-rw-r--r--  0 ryan   staff   10186 Jul 15 06:31 confluent-kafka-1.1.0rc2/tests/test_Consumer.py
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka/
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka/admin/
-rw-r--r--  0 ryan   staff   22967 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/admin/__init__.py
-rw-r--r--  0 ryan   staff    3338 Jul  8 05:41 confluent-kafka-1.1.0rc2/confluent_kafka/__init__.py
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka/avro/
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka/avro/serializer/
-rw-r--r--  0 ryan   staff    1096 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/avro/serializer/__init__.py
-rw-r--r--  0 ryan   staff    8297 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/avro/serializer/message_serializer.py
-rw-r--r--  0 ryan   staff    1006 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/avro/error.py
-rw-r--r--  0 ryan   staff    7013 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/avro/__init__.py
-rw-r--r--  0 ryan   staff   16701 May 30 06:30 confluent-kafka-1.1.0rc2/confluent_kafka/avro/cached_schema_registry_client.py
-rw-r--r--  0 ryan   staff    1508 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/avro/load.py
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka/kafkatest/
-rw-r--r--  0 ryan   staff    3562 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/kafkatest/verifiable_client.py
-rw-r--r--  0 ryan   staff      85 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/kafkatest/__init__.py
-rwxr-xr-x  0 ryan   staff   11581 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/kafkatest/verifiable_consumer.py
-rwxr-xr-x  0 ryan   staff    5109 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/kafkatest/verifiable_producer.py
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka/src/
-rw-r--r--  0 ryan   staff   17446 Jul 19 22:50 confluent-kafka-1.1.0rc2/confluent_kafka/src/Producer.c
-rw-r--r--  0 ryan   staff   12445 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/src/confluent_kafka.h
-rw-r--r--  0 ryan   staff   57695 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/src/Admin.c
-rw-r--r--  0 ryan   staff   68161 Jul 19 22:50 confluent-kafka-1.1.0rc2/confluent_kafka/src/confluent_kafka.c
-rw-r--r--  0 ryan   staff   17936 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/src/AdminTypes.c
-rw-r--r--  0 ryan   staff   45887 Jun 12 08:30 confluent-kafka-1.1.0rc2/confluent_kafka/src/Consumer.c
-rw-r--r--  0 ryan   staff   13001 Mar 27 06:11 confluent-kafka-1.1.0rc2/confluent_kafka/src/Metadata.c
-rw-r--r--  0 ryan   staff     103 Mar 27 06:11 confluent-kafka-1.1.0rc2/MANIFEST.in
-rw-r--r--  0 ryan   staff    8293 Mar 27 06:11 confluent-kafka-1.1.0rc2/README.md
-rwxr-xr-x  0 ryan   staff    1864 Jul 26 08:14 confluent-kafka-1.1.0rc2/setup.py
-rw-r--r--  0 ryan   staff      38 Jul 26 08:17 confluent-kafka-1.1.0rc2/setup.cfg
-rw-r--r--  0 ryan   staff   32984 Mar 27 06:11 confluent-kafka-1.1.0rc2/LICENSE.txt
drwxr-xr-x  0 ryan   staff       0 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka.egg-info/
-rw-r--r--  0 ryan   staff     334 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka.egg-info/PKG-INFO
-rw-r--r--  0 ryan   staff    1556 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka.egg-info/SOURCES.txt
-rw-r--r--  0 ryan   staff     212 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka.egg-info/requires.txt
-rw-r--r--  0 ryan   staff      22 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka.egg-info/top_level.txt
-rw-r--r--  0 ryan   staff       1 Jul 26 08:17 confluent-kafka-1.1.0rc2/confluent_kafka.egg-info/dependency_links.txt

rerunning CI jobs, assuming they pass I'll merge

**Comment by rnpridgeon** [comment]
sdist still looks fine 

 python setup.py sdist
running sdist
running egg_info
writing confluent_kafka.egg-info/PKG-INFO
writing dependency_links to confluent_kafka.egg-info/dependency_links.txt
writing requirements to confluent_kafka.egg-info/requires.txt
writing top-level names to confluent_kafka.egg-info/top_level.txt
reading manifest file 'confluent_kafka.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'test-requirements.txt'
writing manifest file 'confluent_kafka.egg-info/SOURCES.txt'
running check
creating confluent-kafka-1.4.0
creating confluent-kafka-1.4.0/confluent_kafka
creating confluent-kafka-1.4.0/confluent_kafka.egg-info
creating confluent-kafka-1.4.0/confluent_kafka/admin
creating confluent-kafka-1.4.0/confluent_kafka/avro
creating confluent-kafka-1.4.0/confluent_kafka/avro/serializer
creating confluent-kafka-1.4.0/confluent_kafka/kafkatest
creating confluent-kafka-1.4.0/confluent_kafka/schema_registry
creating confluent-kafka-1.4.0/confluent_kafka/serialization
creating confluent-kafka-1.4.0/confluent_kafka/src
creating confluent-kafka-1.4.0/examples
creating confluent-kafka-1.4.0/examples/tests
creating confluent-kafka-1.4.0/tests
creating confluent-kafka-1.4.0/tests/avro
creating confluent-kafka-1.4.0/tests/integration
creating confluent-kafka-1.4.0/tests/integration/schema_registry
creating confluent-kafka-1.4.0/tests/integration/schema_registry/gen
creating confluent-kafka-1.4.0/tests/integration/serialization
creating confluent-kafka-1.4.0/tests/schema_registry
copying files to confluent-kafka-1.4.0...
copying LICENSE.txt -> confluent-kafka-1.4.0
copying MANIFEST.in -> confluent-kafka-1.4.0
copying README.md -> confluent-kafka-1.4.0
copying setup.py -> confluent-kafka-1.4.0
copying confluent_kafka/__init__.py -> confluent-kafka-1.4.0/confluent_kafka
copying confluent_kafka/deserializing_consumer.py -> confluent-kafka-1.4.0/confluent_kafka
copying confluent_kafka/error.py -> confluent-kafka-1.4.0/confluent_kafka
copying confluent_kafka/serializing_producer.py -> confluent-kafka-1.4.0/confluent_kafka
copying confluent_kafka.egg-info/PKG-INFO -> confluent-kafka-1.4.0/confluent_kafka.egg-info
copying confluent_kafka.egg-info/SOURCES.txt -> confluent-kafka-1.4.0/confluent_kafka.egg-info
copying confluent_kafka.egg-info/dependency_links.txt -> confluent-kafka-1.4.0/confluent_kafka.egg-info
copying confluent_kafka.egg-info/requires.txt -> confluent-kafka-1.4.0/confluent_kafka.egg-info
copying confluent_kafka.egg-info/top_level.txt -> confluent-kafka-1.4.0/confluent_kafka.egg-info
copying confluent_kafka/admin/__init__.py -> confluent-kafka-1.4.0/confluent_kafka/admin
copying confluent_kafka/avro/__init__.py -> confluent-kafka-1.4.0/confluent_kafka/avro
copying confluent_kafka/avro/cached_schema_registry_client.py -> confluent-kafka-1.4.0/confluent_kafka/avro
copying confluent_kafka/avro/error.py -> confluent-kafka-1.4.0/confluent_kafka/avro
copying confluent_kafka/avro/load.py -> confluent-kafka-1.4.0/confluent_kafka/avro
copying confluent_kafka/avro/serializer/__init__.py -> confluent-kafka-1.4.0/confluent_kafka/avro/serializer
copying confluent_kafka/avro/serializer/message_serializer.py -> confluent-kafka-1.4.0/confluent_kafka/avro/serializer
copying confluent_kafka/kafkatest/__init__.py -> confluent-kafka-1.4.0/confluent_kafka/kafkatest
copying confluent_kafka/kafkatest/verifiable_client.py -> confluent-kafka-1.4.0/confluent_kafka/kafkatest
copying confluent_kafka/kafkatest/verifiable_consumer.py -> confluent-kafka-1.4.0/confluent_kafka/kafkatest
copying confluent_kafka/kafkatest/verifiable_producer.py -> confluent-kafka-1.4.0/confluent_kafka/kafkatest
copying confluent_kafka/schema_registry/__init__.py -> confluent-kafka-1.4.0/confluent_kafka/schema_registry
copying confluent_kafka/schema_registry/avro.py -> confluent-kafka-1.4.0/confluent_kafka/schema_registry
copying confluent_kafka/schema_registry/error.py -> confluent-kafka-1.4.0/confluent_kafka/schema_registry
copying confluent_kafka/schema_registry/json_schema.py -> confluent-kafka-1.4.0/confluent_kafka/schema_registry
copying confluent_kafka/schema_registry/protobuf.py -> confluent-kafka-1.4.0/confluent_kafka/schema_registry
copying confluent_kafka/schema_registry/schema_registry_client.py -> confluent-kafka-1.4.0/confluent_kafka/schema_registry
copying confluent_kafka/serialization/__init__.py -> confluent-kafka-1.4.0/confluent_kafka/serialization
copying confluent_kafka/src/Admin.c -> confluent-kafka-1.4.0/confluent_kafka/src
copying confluent_kafka/src/AdminTypes.c -> confluent-kafka-1.4.0/confluent_kafka/src
copying confluent_kafka/src/Consumer.c -> confluent-kafka-1.4.0/confluent_kafka/src
copying confluent_kafka/src/Metadata.c -> confluent-kafka-1.4.0/confluent_kafka/src
copying confluent_kafka/src/Producer.c -> confluent-kafka-1.4.0/confluent_kafka/src
copying confluent_kafka/src/confluent_kafka.c -> confluent-kafka-1.4.0/confluent_kafka/src
copying confluent_kafka/src/confluent_kafka.h -> confluent-kafka-1.4.0/confluent_kafka/src
copying examples/__init__.py -> confluent-kafka-1.4.0/examples
copying examples/adminapi.py -> confluent-kafka-1.4.0/examples
copying examples/asyncio.py -> confluent-kafka-1.4.0/examples
copying examples/avro-cli.py -> confluent-kafka-1.4.0/examples
copying examples/avro_consumer.py -> confluent-kafka-1.4.0/examples
copying examples/avro_producer.py -> confluent-kafka-1.4.0/examples
copying examples/confluent_cloud.py -> confluent-kafka-1.4.0/examples
copying examples/consumer.py -> confluent-kafka-1.4.0/examples
copying examples/eos-transactions.py -> confluent-kafka-1.4.0/examples
copying examples/json_consumer.py -> confluent-kafka-1.4.0/examples
copying examples/json_producer.py -> confluent-kafka-1.4.0/examples
copying examples/producer.py -> confluent-kafka-1.4.0/examples
copying examples/protobuf_consumer.py -> confluent-kafka-1.4.0/examples
copying examples/protobuf_producer.py -> confluent-kafka-1.4.0/examples
copying examples/sasl_producer.py -> confluent-kafka-1.4.0/examples
copying examples/user_pb2.py -> confluent-kafka-1.4.0/examples
copying examples/tests/__init__.py -> confluent-kafka-1.4.0/examples/tests
copying examples/tests/conftest.py -> confluent-kafka-1.4.0/examples/tests
copying tests/__init__.py -> confluent-kafka-1.4.0/tests
copying tests/test_Admin.py -> confluent-kafka-1.4.0/tests
copying tests/test_Consumer.py -> confluent-kafka-1.4.0/tests
copying tests/test_KafkaError.py -> confluent-kafka-1.4.0/tests
copying tests/test_Producer.py -> confluent-kafka-1.4.0/tests
copying tests/test_SerializerError.py -> confluent-kafka-1.4.0/tests
copying tests/test_TopicPartition.py -> confluent-kafka-1.4.0/tests
copying tests/test_docs.py -> confluent-kafka-1.4.0/tests
copying tests/test_enums.py -> confluent-kafka-1.4.0/tests
copying tests/test_log.py -> confluent-kafka-1.4.0/tests
copying tests/test_misc.py -> confluent-kafka-1.4.0/tests
copying tests/test_threads.py -> confluent-kafka-1.4.0/tests
copying tests/avro/__init__.py -> confluent-kafka-1.4.0/tests/avro
copying tests/avro/data_gen.py -> confluent-kafka-1.4.0/tests/avro
copying tests/avro/mock_registry.py -> confluent-kafka-1.4.0/tests/avro
copying tests/avro/mock_schema_registry_client.py -> confluent-kafka-1.4.0/tests/avro
copying tests/avro/test_avro_producer.py -> confluent-kafka-1.4.0/tests/avro
copying tests/avro/test_cached_client.py -> confluent-kafka-1.4.0/tests/avro
copying tests/avro/test_message_serializer.py -> confluent-kafka-1.4.0/tests/avro
copying tests/avro/test_mock_client.py -> confluent-kafka-1.4.0/tests/avro
copying tests/avro/test_util.py -> confluent-kafka-1.4.0/tests/avro
copying tests/integration/__init__.py -> confluent-kafka-1.4.0/tests/integration
copying tests/integration/cluster_fixture.py -> confluent-kafka-1.4.0/tests/integration
copying tests/integration/conftest.py -> confluent-kafka-1.4.0/tests/integration
copying tests/integration/integration_test.py -> confluent-kafka-1.4.0/tests/integration
copying tests/integration/schema_registry/__init__.py -> confluent-kafka-1.4.0/tests/integration/schema_registry
copying tests/integration/schema_registry/test_api_client.py -> confluent-kafka-1.4.0/tests/integration/schema_registry
copying tests/integration/schema_registry/test_avro_serializers.py -> confluent-kafka-1.4.0/tests/integration/schema_registry
copying tests/integration/schema_registry/test_json_serializers.py -> confluent-kafka-1.4.0/tests/integration/schema_registry
copying tests/integration/schema_registry/test_proto_serializers.py -> confluent-kafka-1.4.0/tests/integration/schema_registry
copying tests/integration/schema_registry/gen/DependencyTestProto_pb2.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/schema_registry/gen/NestedTestProto_pb2.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/schema_registry/gen/PublicTestProto_pb2.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/schema_registry/gen/Sint32Value_pb2.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/schema_registry/gen/Sint64Value_pb2.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/schema_registry/gen/TestProto_pb2.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/schema_registry/gen/__init__.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/schema_registry/gen/common_proto_pb2.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/schema_registry/gen/exampleProtoCriteo_pb2.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/schema_registry/gen/metadata_proto_pb2.py -> confluent-kafka-1.4.0/tests/integration/schema_registry/gen
copying tests/integration/serialization/__init__.py -> confluent-kafka-1.4.0/tests/integration/serialization
copying tests/integration/serialization/test_serializers.py -> confluent-kafka-1.4.0/tests/integration/serialization
copying tests/schema_registry/__init__.py -> confluent-kafka-1.4.0/tests/schema_registry
copying tests/schema_registry/conftest.py -> confluent-kafka-1.4.0/tests/schema_registry
copying tests/schema_registry/test_api_client.py -> confluent-kafka-1.4.0/tests/schema_registry
copying tests/schema_registry/test_avro_serializer.py -> confluent-kafka-1.4.0/tests/schema_registry
copying tests/schema_registry/test_config.py -> confluent-kafka-1.4.0/tests/schema_registry
copying tests/schema_registry/test_proto.py -> confluent-kafka-1.4.0/tests/schema_registry
Writing confluent-kafka-1.4.0/setup.cfg
creating dist
Creating tar archive
removing 'confluent-kafka-1.4.0' (and everything under it)

**Comment by edenhill** [comment]
I believe the AppVeyor failures are related to including the tests.
It also seems like the tests are now included in the wheels, which they should not be.
Can you verify both of these points?

**Comment by brycedrennan** [comment]
My read of the change to setup.py is that it would create a top-level "tests" package for anyone who installed `confluent_kafka`.

 @rnpridgeon what is the intent of what your doing here?

**Pull request closed without merging**
