### PR TITLE
Performance enhancement by caching fastavro schema parsed on every message serialized & deserialized

### PR DESCRIPTION
**Pull request by bruc3mackenzi3**
The fastavro schema is being re-parsed on each message produced, which is a detriment to performance.  This PR addresses it by caching the parsed fastavro schema instead of the JSON dict schema.

We see a 25% performance enhancement when used with large schemas, and a 5% improvement with small schemas.

### CODE REVIEW

**Comment by bruc3mackenzi3** [comment]
[clabot:check]

**Comment by AndreiLieb** [comment]
@rnpridgeon any updates on this? This is a pretty significant optimization for us.

**Comment by rnpridgeon** [comment]
Good catch @bruc3mackenzi3 , all in all the PR looks good. I'll sanity check it against the Avro integration tests this afternoon for both the py2 and py3 interpreters and if everything works as expected I'll merge. Thanks again for your contribution and I apologize for the hold up on this review.

**Comment by bruc3mackenzi3** [comment]
@rnpridgeon thanks for taking a look and that's great news.  We look forward to having our PR merged.  If you need anything from us in the meantime let us know.

**Comment by rnpridgeon** [comment]
Thanks for your contribution @bruc3mackenzi3

**Pull request merged**
