### PR TITLE
Setup isort and black library

### LINKED ISSUE #1351: automated style checking
we should look at adding automated style checking using `autopep8` or similar.

### PR DESCRIPTION
**Pull request by jairhenrique**
Fixes #1351

### CODE REVIEW

**Comment by mhowlett** [comment]
thanks @jairhenrique ! note that i'm currently working on a branch `serdes` to tidy a lot of stuff up. To avoid merge conflicts i think we'll do the code formatting after that gets merged to master.

**Comment by jairhenrique** [comment]
@mhowlett I move this changes to `serdes` branch and remove source formatting.

**Comment by edenhill** [comment]
Nice :+1:

We'll want this added as one of the build steps in .travis.yml too, replacing the flake8 with the lint check target.
Only need to do this for the Linux source builder.

**Comment by jairhenrique** [comment]
@edenhill done!

**Comment by palfrey** [comment]
@mhowlett What happened to this work? Not seeing it in master?

**Pull request closed without merging**
