### PR TITLE
Update load.py

### PR DESCRIPTION
**Pull request by mak600d**
fix the bug module 'avro.schema' has no attribute 'Parse'

### CODE REVIEW

**Comment by mak600d** [comment]
> It looks like @mak600d hasn't signed our **C**ontributor **L**icense **A**greement, yet.
> 
> > The purpose of a CLA is to ensure that the guardian of a project's outputs has the necessary ownership or grants of rights over all contributions to allow them to distribute under the chosen licence.
> > [Wikipedia](http://en.wikipedia.org/wiki/Contributor_License_Agreement)
> 
> You can read and sign our full Contributor License Agreement [here](http://clabot.confluent.io/cla).
> 
> Once you've signed reply with `[clabot:check]` to prove it.
> 
> Appreciation of efforts,
> 
> clabot

[clabot:check]

**Comment by jeeftor** [comment]
I need this change!!

**Comment by benjaminxscott** [comment]
Having run into this issue, I believe it's due to a recent change with the `avro` dependency which deprecates `avro-python3` in favor of [`avro`](https://pypi.org/project/avro/)

https://avro.apache.org/docs/1.10.0/gettingstartedpython.html

In this new paradigm, I believe this codepath could call `parse()` without having to switch on the python ver

Noting also that the `if` statement in this patch is a no-op

**Comment by jeeftor** [comment]
I cam up with a very bad fix which was rewriting the sys.version to 2 instead of 3... PURE HACK

**Review by mmartinSophos — APPROVED** [review]

**Comment by mhowlett** [comment]
thanks for reporting @jeeftor and sorry for the delay in actioning. this was later resolved by #1006 which I just merged.

**Pull request closed without merging**
