### PR TITLE
Broker loss example consumer failure

### PR DESCRIPTION
**Pull request by johnistan**
This is a reproduction of an error I am having trouble dealing with. If a broker goes down I am unable to successfully consume from any topic that has that broker as a leader. I know this is a core part of the kafka protocol but i am having issues making the python client gracefully handle broker loss. This is causing much pain for my workers. Am I missing something or is this an issue with the client?

added a docker file and compose to help spin up brokers. tox/travis might work. To run:

```
docker-compose build
docker-compose up -d
py.test examples/example_failed_broker.py -sv
```

### CODE REVIEW

**Comment by edenhill** [comment]
Wow, this is great! Thanks for taking the time to set this up!

**Comment by edenhill** [comment]
Where do I find the `test-kafka` image?

```
$ docker-compose up -d
Creating network "confluentkafkapython_default" with the default driver
Pulling kafka1 (test-kafka:latest)...
ERROR: pull access denied for test-kafka, repository does not exist or may require 'docker login'
```

**Comment by johnistan** [comment]
sorry try `docker-compose build` first
the image def is in the pr

**Comment by edenhill** [comment]
what librdkafka version are you using?

**Comment by johnistan** [comment]
using conda

`librdkafka                0.9.4                         0    conda-forge`

**Comment by edenhill** [comment]
Okay, tried to reproduce this with librdkafka master and it seems like the real issue is that it takes more than 30s for the paused broker to have its failure detected by the cluster.
When increasing the timeout to 90s it eventually reassigns the paused broker's partitions to the replicas and consumption continues

**Comment by johnistan** [comment]
Thanks for taking a look. I reran on this with librdkafka master I get correct behavior. With librdkafka 0.9.4 no amount of timeout seems to help.

**Comment by edenhill** [comment]
Ok, that is great news. We're looking to release a new version of librdkafka and python client end of february.

**Pull request closed without merging**
