### PR TITLE
add consume() to AvroConsumer

### PR DESCRIPTION
**Pull request by pxLi**
simply override consume() for to allow decode batch of avro messages.

### CODE REVIEW

**Comment by pxLi** [comment]
[clabot:check]

**Comment by syelda** [comment]
This would be very useful to have! Any update on when this might be added?

**Comment by meridional** [comment]
Any update on this? Seems to be a simple diff to review. And it would be extremely useful.. (It's called AvroConsumer after all.)

**Comment by rnpridgeon** [comment]
This will be covered with generic serde support, #502

**Pull request closed without merging**
