### PR TITLE
project description in pypi docs

### PR DESCRIPTION
**Pull request by Bowrna**
Added long description into setuptools so that it will be added in pypi description

### CODE REVIEW

**Comment by Bowrna** [comment]
[clabot:check]

**Comment by Bowrna** [comment]
[clabot:check]

**Comment by Bowrna** [comment]
Issue : https://github.com/confluentinc/confluent-kafka-python/issues/1145
I have not run any test to verify this. It would be helpful if someone can tell me how i can test this.

**Comment by rbarrois** [comment]
@Bowrna I think you can test it using pyroma (`pip install pyroma` + `pyroma .`), it would say "The package's long_description is quite short" if the README is missing.

You may also run `python setup.py sdist`, and check the contents of the `PKG-INFO` file in the generated tar.gz archive.

By the way, thanks a lot for taking over the issue I had submitted and forgot to take care of 😊

**Comment by Bowrna** [comment]
@rbarrois thank you so much your reply. Sure i will do the steps that you have shared and update in this thread.

**Comment by mhowlett** [comment]
thanks for the PR! i noticed this too - definitely need to get it fixed. side note: relevant people are on leave ATM, there may be a delay getting this merged.

**Comment by jliunyu** [comment]
Thanks @Bowrna, I will merge the PR after the test result is updated.

**Comment by Bowrna** [comment]
@rbarrois i have tested the PR with pyroma like you have suggested and got the below response. Verified the PKG-INFO file inside .tar.gz file in dist folder. It contains description in it.
```
------------------------------
Checking .
Found confluent-kafka
------------------------------
Your package does not have keywords data.
------------------------------
Final rating: 9/10
Cottage Cheese
------------------------------
```
@mhowlett @jliunyu thank you. if there is anything that i have to fix in this PR, please update in this thread.

**Pull request merged**
