### PR TITLE
Add 'get_metadata' to Producer and Consumer.

### PR DESCRIPTION
**Pull request by stephan-hof**
Hi,

in my application the need came up to get some metadata from the broker.
As far as I can see, `confluent-kafka-python` has no API to retrieve this easily.
This pull request wraps the `rd_kafka_metadata` and returns the corresponding structures in python.

### CODE REVIEW

**Comment by stephan-hof** [comment]
Anything you need from me to get it accepted ? 
I thought I have signed the CLA. [clabot:check]

**Comment by edenhill** [comment]
Thank you for this PR, @stephan-hof !

The plan is to add a richer metadata API to librdkafka (also supporting KIP-4) and the Python bindings should make use of this new API rather than the old one, so I'm going to need to put this PR on hold for a while.

**Comment by jeffwidman** [comment]
> The plan is to add a richer metadata API to librdkafka (also supporting KIP-4)

Is there an associated issue or PR to track progress on this?

**Comment by edenhill** [comment]
Added issue to track it:
https://github.com/edenhill/librdkafka/issues/1158

**Comment by stephan-hof** [comment]
All of what has been said so far makes much sense to me.
So I guess the pull request in its current form will never be accepted, because he is using a deprecated API. When the new API is there I'm pretty sure the code to get the metadata will look differently.
=> I'll close this pull request and may add a new one when the new API is there.
Until the new API is there I'll use my branch where this pull request originates from.

**Comment by edenhill** [comment]
Thank you!

**Comment by tbsaunde** [comment]
I'm not sure it really makes a lot of sense to hold off here.  Looking at the librdkafka issue and the kafka wire protocol changes to the metadata API it seems like it should be pretty easy to keep compatability with python users while changing to the newer librdkafka API when implemented, and exposing more information from the brokers to python clients.  In any case the old librdkafka API can't go away until a soname bump if that ever happens, and  there's plenty of C users of this API already, so having one more consumer that eventually needs to change to a better API doesn't seem like a big deal.  its also worth considering that there's already 8 months of librdkafka versions out there that only provide the rd_kafka_metadata() API, so if someone can only change the python wrapper for some reason falling back to the older API there would be useful for them.  So it seems to me it would be good to merge something like this pr and then work on adding new API to librdkafka and changing consumers to use it.

**Comment by edenhill** [comment]
You are right, sorry for the long delay.
We'll revisit this PR shortly.

**Comment by edenhill** [comment]
We should revamp this and change it to mimic the java ListTopics() API

**Comment by tbsaunde** [comment]
I did that in #309 (I don't know how to update someone else's PR)

**Pull request closed without merging**
