### PR TITLE
Issue-674 fix indenting in SerializerError

### PR DESCRIPTION
**Pull request by ferozed**
This PR fixes the indenting in the SerializerError class.

### CODE REVIEW

**Comment by ferozed** [comment]
[clabot:check]

**Comment by rnpridgeon** [comment]
Thanks for the PR @ferozed  , could you add a quick integration test as well.

**Comment by ferozed** [comment]
Owners, can you please merge this?

**Comment by edenhill** [comment]
Thank you for your contribution!

**Pull request merged**
