### PR TITLE
Fix constructor doc (#321)

### PR DESCRIPTION
**Pull request by rnpridgeon**

### CODE REVIEW

**Comment by rnpridgeon** [comment]
So silently accept kwargs then without advertising this capability in the docs? Is that the right move or perhaps a brief description linking the rdkafka configuration page

**Comment by edenhill** [comment]
we should link to CONFIGURATION.md, but that is for the config dict.
The kwargs is really just an alternative to the dict, it takes the same keys (but none of the standard config properties will work since they contain dots . ).

You can do this:
`p = Producer({"bootstrap.servers":"gnägg"}, logger=mylogger)`
which is identical to:
`p = Producer({"bootstrap.servers":"gnägg", "logger": mylogger})`

so I don't think there is any need to expose kwargs.

**Comment by rnpridgeon** [comment]
To encourage good behavior perhaps its a good idea to expose kwargs referencing the configs specific to the python binding in the [docs](docs/index.rst)

**Comment by rnpridgeon** [comment]
There are some extra formatting changes to appease the sphinx gods

**Pull request merged**
