### PR TITLE
Tox 

### PR DESCRIPTION
**Pull request by mieciu**
Following issue #47 I'd like to suggest introducing tox as a testing tool.

Feel free to install tox (with `pip`) and simply run `tox` from the root directory. It will download both `pytest` and `flake` automatically for you.

Please note that this PR is just a loose suggestion. I'd like to hear some kind of feedback from project maintainers to have green light on polishing this further on.

### CODE REVIEW

**Comment by edenhill** [comment]
This looks good.
@ewencp Any comments?
@mieciu Can you sign the CLA?

**Comment by ewencp** [comment]
@mieciu Sorry, CLABot is misbehaving. You can find the CLA to sign [here](http://clabot.confluent.io/cla).

tox file looks good and I've tested. We've definitely got some flake8 cleanup to do. Testing on 3.5.2 is also testing, but just to get the tox changes in, this LGTM. Other potentially missing piece is something in a README, although finding how to set this up wasn't all that tough and probably many python library devs are already familiar.

**Comment by edenhill** [comment]
Yes, please add Tox setup instructions in tests/README.md
Thanks

**Comment by edenhill** [comment]
Whoops, didnt mean to close it.
@mieciu If you sign the CLA we'd be happy to merge this.

**Comment by mieciu** [comment]
I've just signed the CLA and updated `README` sections you were  asking for.

**Comment by edenhill** [comment]
Awesome, thanks for this!

**Comment by edenhill** [comment]
Also +1 for squashing your commits :)

**Pull request merged**
