### PR TITLE
Fix the MappingProxyType error when converting schema to JSON

### LINKED ISSUE #610: confluent-kafka 1.0.0 is incompatible with avro-python3 1.9.0
Description
===========

Since version 1.9.0 of avro-python3 [Schema.props](https://github.com/apache/avro/blob/3c76495e9524ef322726d03d7ee406be89e8fde0/lang/py3/avro/schema.py#L211) returns a `MappingProxyType` object which not json-serializable by default and leads to following exceptions:

```
...
  File "<venv>/lib/python3.7/site-packages/confluent_kafka/avro/__init__.py", line 80, in produce
    value = self._serializer.encode_record_with_schema(topic, value_schema, value)
  File "<venv>/lib/python3.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 105, in encode_record_with_schema
    schema_id = self.registry_client.register(subject, schema)
  File "<venv>/lib/python3.7/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 214, in register
    body = {'schema': json.dumps(avro_schema.to_json())}
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type mappingproxy is not JSON serializable
```

To fix this, the registry client (and everything else) should use [`Schema.__str__`](https://github.com/apache/avro/blob/3c76495e9524ef322726d03d7ee406be89e8fde0/lang/py3/avro/schema.py#L218) to get the json representation instead of calling `json.dumps(avro_schema.to_json())`

### PR DESCRIPTION
**Pull request by choogeboom**
`avro.schema.Schema.to_json` uses `MappingProxyType`, which is not compatible with `json.dumps`. ~This PR solves the issue in the same way that the `avro` library solves it, by using the `MappingProxyEncoder` in the `avro` library.~ Unfortunately that was causing appveyor to fail, so I'm just converting to JSON with the `str` function, which is the same under the hood.

fixes #610

### CODE REVIEW

**Review by Incognito — APPROVED** [review]
Hey folks, this is an easy way to fix an entire broken feature. Can we get eyes on it?

**Comment by choogeboom** [comment]
I've given up hope on this PR, and migrated my code to start using [`SchemaRegistryClient`](https://docs.confluent.io/current/clients/confluent-kafka-python/index.html#schemaregistry-client) instead, which sidesteps this whole issue.

**Comment by Incognito** [comment]
We did this too actually, but it was a shame that my team had to re-work large parts of their work because of it.

**Comment by mhowlett** [comment]
> I'm just converting to JSON with the str function, which is the same under the hood.

https://github.com/apache/avro/blob/master/lang/py3/avro/schema.py#L219

**Review by mhowlett — COMMENTED** [review]
LGTM (hopefully not missing anything important)

**Pull request merged**
